# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Upgrade Ansible role.
#
# The Webarchitects Upgrade Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Upgrade Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Upgrade Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_CALLBACK_RESULT_FORMAT: "yaml"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  ANSIBLE_FORCE_COLOR: "1"
  ANSIBLE_REMOTE_TMP: "/tmp"
  ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"
  MOLECULE_VERBOSITY: "3"
  PY_COLORS: "1"
before_script:
  - whoami
  - pwd
  - which ansible
  - ansible --version
  - which yamllint
  - yamllint --version
  - which molecule
  - molecule --version
stages:
  - bookworm
  # - bullseye
  - jammy
  - trixie
bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20230822
  stage: bookworm
  script:
    - molecule test
# bullseye:
#   image: registry.git.coop/webarch/containers/images/bullseye:20230822
#   stage: bullseye
#   script:
#     - molecule test
jammy:
  image: registry.git.coop/webarch/containers/images/jammy:20230822
  stage: jammy
  script:
    - molecule test
trixie:
  image: registry.git.coop/webarch/containers/images/trixie:20230822
  stage: trixie
  script:
    - molecule test
...
