# Copyright 2018-2025 Chris Croome
#
# This file is part of the Webarchitects Upgrade Ansible role.
#
# The Webarchitects Upgrade Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Upgrade Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Upgrade Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_ANY_ERRORS_FATAL: "1"
  ANSIBLE_CALLBACK_RESULT_FORMAT: "yaml"
  ANSIBLE_DEFAULT_VERBOSITY: "1"
  ANSIBLE_DIFF_ALWAYS: "1"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  # ANSIBLE_ERROR_ON_UNDEFINED_VARS: "1"
  ANSIBLE_FORCE_COLOR: "1"
  ANSIBLE_INJECT_FACT_VARS: "0"
  ANSIBLE_NOCOWS: "1"
  ANSIBLE_REMOTE_TMP: "/tmp"
  ANSIBLE_ROLES_PATH: "${CI_PROJECT_DIR}/..:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles"
  ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"
  DEBIAN_FRONTEND: noninteractive
  # DEFAULT_MANAGED_STR: "Ansible managed"
  MOLECULE_VERBOSITY: "0"
  PRE_COMMIT_COLOR: always
  PY_COLORS: "1"
before_script:
  - whoami
  - pwd
  - which pipx
  - pipx list
  - which jc
  - jc --version
  - which ansible
  - ansible --version
  - which yamllint
  - yamllint --version
  - which molecule
  - molecule --version
stages:
  # An older version of containers to test upgrades
  # https://git.coop/webarch/containers#docker-containers
  - 20250802_bookworm
  - 20250802_jammy
  - 20250802_noble
  - 20250802_trixie
  # A recent version of the containers
  - 20250821_bookworm
  - 20250821_jammy
  - 20250821_noble
  - 20250821_trixie
20250802_bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20250802
  stage: 20250802_bookworm
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
20250802_jammy:
  image: registry.git.coop/webarch/containers/images/jammy:20250802
  stage: 20250802_jammy
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
20250802_noble:
  image: registry.git.coop/webarch/containers/images/noble:20250802
  stage: 20250802_noble
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
20250802_trixie:
  image: registry.git.coop/webarch/containers/images/trixie:20250802
  stage: 20250802_trixie
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
20250821_bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20250821
  stage: 20250821_bookworm
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
20250821_jammy:
  image: registry.git.coop/webarch/containers/images/jammy:20250821
  stage: 20250821_jammy
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
20250821_noble:
  image: registry.git.coop/webarch/containers/images/noble:20250821
  stage: 20250821_noble
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
20250821_trixie:
  image: registry.git.coop/webarch/containers/images/trixie:20250821
  stage: 20250821_trixie
  script:
    - pre-commit install
    - pre-commit run --all-files
    - molecule test
...
