# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Upgrade Ansible role.
#
# The Webarchitects Upgrade Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Upgrade Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Upgrade Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Changelog tasks
  block:

    - name: Ensure that a Changelog backup directory is present
      ansible.builtin.file:
        path: /root/.Changelog
        state: directory
        mode: "0700"
        owner: root
        group: root

    - name: Set fact for the date and time
      ansible.builtin.set_fact:
        upgrade_changelog_date: "{{ ansible_date_time.date }}"
        upgrade_changelog_time: "{{ ansible_date_time.iso8601_micro }}"

    - name: Check if the Changelog exists
      ansible.builtin.stat:
        path: /root/Changlog
      register: upgrade_changelog_path

  tags:
    - upgrade
...
