# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Upgrade Ansible role.
#
# The Webarchitects Upgrade Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Upgrade Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Upgrade Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Changelog tasks
  block:

    - name: Ensure that a Changelog backup directory is present
      ansible.builtin.file:
        path: /root/.Changelog
        state: directory
        mode: "0700"
        owner: root
        group: root

    - name: Set fact for the date and time
      ansible.builtin.set_fact:
        upgrade_changelog_date: "{{ ansible_facts.date_time.date }}"
        upgrade_changelog_time: "{{ ansible_facts.date_time.iso8601_micro }}"

    - name: Set fact for the user name using GITLAB_USER_LOGIN
      ansible.builtin.set_fact:
        upgrade_changelog_user: "{{ ansible_facts.env.GITLAB_USER_LOGIN }}"
      when: ansible_facts.env.GITLAB_USER_LOGIN is defined

    - name: Set fact for the user name using SUDO_USER
      ansible.builtin.set_fact:
        upgrade_changelog_user: "{{ ansible_facts.env.SUDO_USER }}"
      when: ansible_facts.env.SUDO_USER is defined

    - name: Set fact for the user name using USER
      ansible.builtin.set_fact:
        upgrade_changelog_user: "{{ ansible_facts.env.USER }}"
      when:
        - ansible_facts.env.USER is defined
        - ansible_facts.env.GITLAB_USER_LOGIN is not defined
        - ansible_facts.env.SUDO_USER is not defined

    - name: Set fact for the username to root
      ansible.builtin.set_fact:
        upgrade_changelog_user: root
      when:
        - ansible_facts.effective_user_id == 0
        - ansible_facts.env.USER is not defined
        - ansible_facts.env.GITLAB_USER_LOGIN is not defined
        - ansible_facts.env.SUDO_USER is not defined

    - name: Check if the Changelog exists
      ansible.builtin.stat:
        path: /root/Changelog
      register: upgrade_changelog_path

    - name: Create an initial Changelog
      block:

        - name: Template the Changelog when it doesn't exist
          ansible.builtin.template:
            src: Changelog.j2
            dest: /root/Changelog
            mode: "0600"
            owner: root
            group: root

        - name: Check if the Changelog exists
          ansible.builtin.stat:
            path: /root/Changelog
          register: upgrade_changelog_path

      when: not upgrade_changelog_path.stat.exists

  tags:
    - upgrade
...
