---
- name: Update package lists in the chroot
  command: chroot /chroot apt-get -qq update
  register: upgrade_chroot_apt_get_update
  tags:
    - upgrade
    - chroot

- debug:
    msg: "Standard out from `chroot /chroot apt-get -qq update` : {{ upgrade_chroot_apt_get_update.stdout }}"
    verbosity: 1
  tags:
    - upgrade
    - chroot

- debug:
    msg: "Standard error from `chroot /chroot apt-get -qq update` : {{ upgrade_chroot_apt_get_update.stderr }}"
    verbosity: 1
  tags:
    - upgrade
    - chroot

- name: Dist-upgrade in the chroot
  command: chroot /chroot apt-get dist-upgrade -y 
  register: upgrade_chroot_apt_get_dist_upgrade
  tags:
    - upgrade
    - chroot

- debug:
    msg: "Standard out from `chroot /chroot apt-get dist-upgrade -y` : {{ upgrade_chroot_apt_get_dist_upgrade.stdout }}"
    verbosity: 1
  tags:
    - upgrade
    - chroot

- debug:
    msg: "Standard error from `chroot /chroot apt-get dist-upgrade -y` : {{ upgrade_chroot_apt_get_dist_upgrade.stderr }}"
    verbosity: 1
  tags:
    - upgrade
    - chroot
