---
- name: Upgrade chroot tasks
  block:

    - name: Dist-upgrade in the chroot  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.command: >-
        chroot {{ upgrade_chroot }} apt-get -fyqo Dpkg::Options::='--force-confdef --force-confold' dist-upgrade
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: upgrade_chroot_apt_get_dist_upgrade
      changed_when: ( "The following packages will be upgraded" in upgrade_chroot_apt_get_dist_upgrade.stdout )

    - name: Apt autoremove in the chroot  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.command: "chroot {{ upgrade_chroot }} apt autoremove -yfq"
      environment:
        DEBIAN_FRONTEND: noninteractive
      changed_when: false
      register: upgrade_chroot_apt_autoremove

    - name: Remove set GID from files  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.shell: "for i in $( find {{ upgrade_chroot }} -perm -2000 ); do chmod g-s $i; done"
      changed_when: false

    - name: Remove set UID from files  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.shell: "for i in $( find {{ upgrade_chroot }} -perm -4000 ); do chmod u-s $i; done"
      changed_when: false

  tags:
    - upgrade
...
