# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Upgrade Ansible role.
#
# The Webarchitects Upgrade Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Upgrade Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Upgrade Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Chroot tasks
  block:

    - name: Update package lists in the chroot  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.command: "chroot {{ upgrade_chroot }} apt-get -qq update"
      environment:
        PATH: /usr/sbin:/usr/bin:/sbin:/bin
      check_mode: false
      changed_when: false
      register: upgrade_chroot_apt_get_update

    - name: Check for updates in the chroot using apt-get -fqqs dist-upgrade  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.command: "chroot {{ upgrade_chroot }} apt-get -fqqs dist-upgrade"
      environment:
        PATH: /usr/sbin:/usr/bin:/sbin:/bin
      check_mode: false
      changed_when: false
      register: upgrade_chroot_packages_command

    - name: Include the chroot upgrade tasks
      ansible.builtin.include_tasks: chroot_upgrade.yml
      when: upgrade_chroot_packages_command.stdout_lines | length > 0

  tags:
    - upgrade
...
