---
- name: Update and upgrade Debian
  block:

    - name: Include the apt role when ansible_local.bash is not defined
      ansible.builtin.include_role:
        name: apt
        tasks_from: local_facts.yml
      when: ansible_local.bash is not defined

    - name: Update the apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      check_mode: false
      changed_when: false

    # Unlike `apt-show-versions -b -u` the following will also list new packages
    - name: Check for updates and new packages using apt-get dist-upgrade -q -s  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.command: apt-get -fq dist-upgrade -s
      environment:
        DEBIAN_FRONTEND: noninteractive
      check_mode: false
      changed_when: false
      register: upgrade_packages_command

    - name: Debugging
      ansible.builtin.debug:
        var: upgrade_packages_command
        verbosity: 3

    - name: Include the upgrade tasks
      ansible.builtin.include_tasks: upgrade.yml
      when: upgrade_packages_command.stdout_lines | last != "0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded."

    - name: Check the existance of the chroot path
      ansible.builtin.stat:
        path: "{{ upgrade_chroot }}"
      register: upgrade_chroot_path

    - name: Check that apt-get exists in the chroot
      ansible.builtin.stat:
        path: "{{ upgrade_chroot }}/usr/bin/apt-get"
      register: upgrade_chroot_apt_path

    - name: Conditionally include chroot tasks
      ansible.builtin.include_tasks: chroot.yml
      when:
        - upgrade_chroot_path.stat.exists | bool
        - upgrade_chroot_apt_path.stat.exists | bool

  when: upgrade | bool
  tags:
    - upgrade
...
