---
- name: Update and upgrade Debian
  block:

    - name: Update the apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      check_mode: false
      changed_when: false

    # Unlike `apt-show-versions -b -u` the following will also list new packages
    - name: Check for updates and new packages using apt-get -fqqs dist-upgrade  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.command: apt-get -fqqs dist-upgrade
      environment:
        DEBIAN_FRONTEND: noninteractive
        PATH: /bin:/sbin:/usr/bin:/usr/sbin
      check_mode: false
      changed_when: false
      register: upgrade_packages_command

    - name: Include the upgrade tasks
      ansible.builtin.include_tasks: upgrade.yml
      when: upgrade_packages_command.stdout_lines | length > 0

    - name: Check the existance of the chroot path
      ansible.builtin.stat:
        path: "{{ upgrade_chroot }}"
      register: upgrade_chroot_path

    - name: Check that apt-get exists in the chroot
      ansible.builtin.stat:
        path: "{{ upgrade_chroot }}/usr/bin/apt-get"
      register: upgrade_chroot_apt_path
      when: upgrade_chroot_path.stat.exists | bool

    - name: Conditionally include chroot tasks
      ansible.builtin.include_tasks: chroot.yml
      when: upgrade_chroot_apt_path.stat.exists | bool

    - name: Include the reboot tasks
      ansible.builtin.include_tasks: reboot.yml
      when:
        - upgrade_reboot is defined
        - upgrade_reboot | bool

  when: upgrade | bool
  tags:
    - upgrade
...
