---
- name: Update and upgrade Debian
  block:

    - name: Packages present
      ansible.builtin.apt:
        pkg:
          - needrestart
        state: present

    - name: Update the apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 0
      check_mode: false
      changed_when: false

    # Unlike `apt-show-versions -b -u` the following will also list new packages
    - name: Check for updates and new packages using apt-get -fqqs dist-upgrade  # noqa yaml[comments] command-instead-of-module
      ansible.builtin.command: apt-get -fqqs dist-upgrade
      environment:
        DEBIAN_FRONTEND: noninteractive
        PATH: /usr/sbin:/usr/bin:/sbin:/bin
      check_mode: false
      changed_when: false
      register: upgrade_packages_command

    - name: Include the upgrade tasks
      ansible.builtin.include_tasks: upgrade.yml
      when: upgrade_packages_command.stdout_lines | length > 0

    - name: Check the existance of the chroot path
      ansible.builtin.stat:
        path: "{{ upgrade_chroot }}"
      register: upgrade_chroot_path

    - name: Chroot tasks
      block:

        - name: Check that apt-get exists in the chroot
          ansible.builtin.stat:
            path: "{{ upgrade_chroot }}/usr/bin/apt-get"
          register: upgrade_chroot_apt_path

        - name: Conditionally include chroot tasks
          ansible.builtin.include_tasks: chroot.yml
          when: upgrade_chroot_apt_path.stat.exists | bool

      when: upgrade_chroot_path.stat.exists | bool

    - name: Check if /usr/sbin/needrestart is present
      ansible.builtin.stat:
        path: /usr/sbin/needrestart
      register: upgrade_needrestart_bin

    - name: Restart services and reboot
      block:

        - name: Include the restart tasks
          ansible.builtin.include_tasks: restart.yml
          when: not upgrade_reboot | bool

        - name: Include the reboot tasks
          ansible.builtin.include_tasks: reboot.yml
          when: upgrade_reboot | bool

      when: upgrade_needrestart_bin.stat.exists | bool

  when: upgrade | bool
  tags:
    - upgrade
...
