---
- name: Munin tasks
  block:

    - name: Delete the apt state file
      ansible.builtin.file:
        path: /var/lib/munin-node/plugin-state/nobody/plugin-apt.state
        state: absent
      register: upgrade_apt_state

    - name: Delete the apt_all state file
      ansible.builtin.file:
        path: /var/lib/munin-node/plugin-state/nobody/plugin-apt_all.state
        state: absent
      register: upgrade_apt_all_state

    - name: Munin tasks
      block:

        - name: Check the Munin apt_all plugin output
          ansible.builtin.command: munin-run apt_all
          args:
            chdir: /etc/munin/plugins
          environment:
            PATH: /bin:/sbin:/usr/bin:/usr/sbin
          register: upgrade_munin_run_apt_all
          check_mode: false
          changed_when: false

        - name: Debugging
          block:

            - name: Standard out from munin-run apt_all
              ansible.builtin.debug:
                var: upgrade_munin_run_apt_all.stdout

            - name: Standard error from munin-run apt_all
              ansible.builtin.debug:
                var: upgrade_munin_run_apt_all.stderr

          when: >-
            ( ansible_verbosity > 1 ) and (
            ( upgrade_munin_run_apt_all.stdout is defined and upgrade_munin_run_apt_all.stdout | length > 0 ) or
            ( upgrade_munin_run_apt_all.stderr is defined and upgrade_munin_run_apt_all.stderr | length > 0 ) )

      when: >-
        ( upgrade_apt_state.changed | bool ) or
        ( upgrade_apt_all_state.changed | bool )

  tags:
    - upgrade
    - munin
...
