---
- name: Delete the apt state file
  ansible.builtin.file:
    path: /var/lib/munin-node/plugin-state/nobody/plugin-apt.state
    state: absent
  register: upgrade_apt_state
  tags:
    - upgrade
    - munin

- name: Delete the apt_all state file
  ansible.builtin.file:
    path: /var/lib/munin-node/plugin-state/nobody/plugin-apt_all.state
    state: absent
  register: upgrade_apt_all_state
  tags:
    - upgrade
    - munin

- name: Munin tasks
  block:

    - name: Check the Munin apt_all plugin output
      ansible.builtin.command: munin-run apt_all
      args:
        chdir: /etc/munin/plugins
      environment:
        PATH: /bin:/sbin:/usr/bin:/usr/sbin
      register: upgrade_munin_run_apt_all
      check_mode: false

    - name: Standard out from munin-run apt_all
      ansible.builtin.debug:
        msg: "Standard out from `munin-run apt_all` : {{ upgrade_munin_run_apt_all.stdout }}"
        verbosity: 2
      when:
        - upgrade_munin_run_apt_all.stdout is defined
        - upgrade_munin_run_apt_all.stdout | length > 0

    - name: Standard error from munin-run apt_all
      ansible.builtin.debug:
        msg: "Standard error from `munin-run apt_all` : {{ upgrade_munin_run_apt_all.stderr }}"
        verbosity: 2
      when:
        - upgrade_munin_run_apt_all.stderr is defined
        - upgrade_munin_run_apt_all.stderr | length > 0

  when: (upgrade_apt_state.changed | bool) or (upgrade_apt_all_state.changed | bool)
  tags:
    - upgrade
    - munin
...
