---
- name: Delete the apt state file
  file:
    path: /var/lib/munin-node/plugin-state/nobody/plugin-apt.state
    state: absent
  register: upgrade_apt_state
  tags:
    - upgrade
    - munin

- name: Delete the apt_all state file
  file:
    path: /var/lib/munin-node/plugin-state/nobody/plugin-apt_all.state
    state: absent
  register: upgrade_apt_all_state
  tags:
    - upgrade
    - munin

- name: Munin tasks
  block:

    - name: Check the Munin apt_all plugin output
      command: munin-run apt_all
      args:
        chdir: /etc/munin/plugins
      environment:
        PATH: /bin:/sbin:/usr/bin:/usr/sbin
      register: upgrade_munin_run_apt_all
      check_mode: false

    - debug:
        msg: "Standard out from `munin-run apt_all` : {{ upgrade_munin_run_apt_all.stdout }}"
        verbosity: 1
      when: upgrade_munin_run_apt_all is defined

    - debug:
        msg: "Standard error from `munin-run apt_all` : {{ upgrade_munin_run_apt_all.stderr }}"
        verbosity: 1
      when: upgrade_munin_run_apt_all is defined

  when: upgrade_apt_state.changed or upgrade_apt_all_state.changed
  tags:
    - upgrade
    - munin
...
