---
- name: Reboot
  block:

    - name: Rebooting
      block:

        - name: Rebooting
          ansible.builtin.debug:
            msg:
              - "{{ upgrade_needrestart_yaml['NEEDRESTART-KCUR'] }} is the current running kernel"
              - "{{ upgrade_needrestart_yaml['NEEDRESTART-KEXP'] }} is the expected kernel, rebooting"

        - name: Reboot when NEEDRESTART-KSTA is 3
          ansible.builtin.reboot:

      when:
        - upgrade_needrestart_yaml['NEEDRESTART-KSTA'] is defined
        - upgrade_needrestart_yaml['NEEDRESTART-KSTA'] == "3"

  tags:
    - upgrade
...
