# Copyright 2018-2026 Chris Croome
#
# This file is part of the Webarchitects Upgrade Ansible role.
#
# The Webarchitects Upgrade Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Upgrade Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Upgrade Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Reboot
  block:

    - name: Rebooting
      block:

        - name: Rebooting
          ansible.builtin.debug:
            msg:
              - "{{ upgrade_needrestart_yaml.running_kernel_version }} is the current running kernel"
              - "{{ upgrade_needrestart_yaml.expected_kernel_version }} is the expected kernel, rebooting"

        - name: Reboot
          ansible.builtin.reboot:

        - name: Wait for the server to come back up
          ansible.builtin.wait_for_connection:
            delay: 30
            sleep: 5
            timeout: 300
          register: upgrade_reboot_elapsed

        - name: Debug upgrade_reboot_elapsed
          ansible.builtin.debug:
            var: upgrade_reboot_elapsed
            verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"
          tags:
            - debug

      when:
        - upgrade_needrestart_yaml.kernel_status is defined
        - upgrade_needrestart_yaml.kernel_status == 3

  tags:
    - upgrade
...
