# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Upgrade Ansible role.
#
# The Webarchitects Upgrade Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Upgrade Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Upgrade Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Restart services
  block:

    - name: Systemd daemon-reexec
      ansible.builtin.systemd:
        daemon_reexec: true
        daemon_reload: true
      when: upgrade_systemd_daemon_reexec | bool

    - name: Restart systemd services
      ansible.builtin.systemd:
        name: "{{ upgrade_service }}"
        state: restarted
      loop: "{{ upgrade_services }}"
      loop_control:
        loop_var: upgrade_service
      when: >-
        ( upgrade_restart_skip is not defined ) or
        ( upgrade_service not in upgrade_restart_skip )

    - name: A reboot is required
      ansible.builtin.debug:
        msg:
          - "{{ upgrade_needrestart_yaml['NEEDRESTART-KCUR'] }} is the current running kernel"
          - "{{ upgrade_needrestart_yaml['NEEDRESTART-KEXP'] }} is the expected kernel"
      when:
        - upgrade_needrestart_yaml['NEEDRESTART-KSTA'] is defined
        - upgrade_needrestart_yaml['NEEDRESTART-KSTA'] == "3"

  tags:
    - upgrade
...
