---
- name: Restart services
  block:

    - name: Run needrestart
      ansible.builtin.command: needrestart -bqr a
      environment:
        PATH: /usr/sbin:/usr/bin:/sbin:/bin
      check_mode: false
      changed_when: false
      register: upgrade_needrestart_command

    - name: Restart systemd services
      ansible.builtin.systemd_service:
        name: "{{ upgrade_restart_services | default([]) + [upgrade_needrestart_line | regex_replace('^NEEDRESTART-SVC: ') | regex_replace('.service$')] }}"
        state: restarted
      when:
        - upgrade_needrestart_line is regex('^NEEDRESTART-SVC')
        - upgrade_needrestart_line is regex('service$')
      loop: "{{ upgrade_needrestart_command.stdout_lines }}"
      loop_control:
        loop_var: upgrade_needrestart_line

  tags:
    - upgrade
...
