---
- name: Upgrade Debian packages
  block:

    - name: Print the list of packages to be upgraded
      ansible.builtin.debug:
        var: upgrade_pkgs

    - name: Dist upgrade
      ansible.builtin.apt:
        upgrade: dist
        autoclean: true
        autoremove: true
        update_cache: false
        dpkg_options: force-confdef,force-confold
      environment:
        DEBIAN_FRONTEND: noninteractive
        PATH: /usr/sbin:/usr/bin:/sbin:/bin
      register: upgrade_dist_upgrade

    # The logchange script is in the https://git.coop/webarch/scripts repo
    - name: Check the existance of /usr/local/bin/logchange
      ansible.builtin.stat:
        path: /usr/local/bin/logchange
      register: upgrade_logchange

    - name: Update the Changelog
      ansible.builtin.command: "logchange '{{ upgrade_pkgs | join | ansible.builtin.quote }} : updated'"
      when: upgrade_logchange.stat.exists | bool

    - name: Restart Docker if it has been updated
      ansible.builtin.service:
        name: docker
        state: restarted
      when: >-
        ( "docker-ce" in upgrade_pkgs ) or
        ( "containerd.io" in upgrade_pkgs )

    - name: Check the existance of /etc/munin/plugins/apt_all
      ansible.builtin.stat:
        path: /etc/munin/plugins/apt_all
      register: upgrade_munin_plugin_apt_all

    - name: Conditionally include munin tasks
      ansible.builtin.include_tasks: munin.yml
      when: upgrade_munin_plugin_apt_all.stat.exists | bool

  tags:
    - upgrade
...
