# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Upgrade Ansible role.
#
# The Webarchitects Upgrade Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Upgrade Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Upgrade Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  # become: true
  connection: local
  # gather_facts: true
  hosts:
    - localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Dist upgrade
      ansible.builtin.apt:
        upgrade: dist
        autoclean: true
        autoremove: true
        update_cache: false
        dpkg_options: force-confdef,force-confold
      environment:
        DEBIAN_FRONTEND: noninteractive
        PATH: /usr/sbin:/usr/bin:/sbin:/bin
      register: molecule_dist_upgrade
      failed_when: molecule_dist_upgrade.changed | bool

    - name: Check if the Changelog exists
      ansible.builtin.stat:
        path: /root/Changelog
      register: molecule_changelog_path
      failed_when: not molecule_changelog_path.stat.exists | bool

    - name: Print /root/Changelog
      block:

        - name: Slurp a base64 encoded version of the file
          ansible.builtin.slurp:
            src: /root/Changelog
          register: molecule_changelog_b64encoded

        - name: Decode the base64 encoded version of the changelog, split it by lines and set an array  # noqa: no-tabs
          ansible.builtin.set_fact:
            molecule_changelog: "{{ ( molecule_changelog_b64encoded['content'] | b64decode | trim | regex_replace('\t', '        ') ).split('\n') }}"

        - name: Print the Changelog contents
          ansible.builtin.debug:
            var: molecule_changelog

      when: molecule_changelog_path.stat.exists

...
